import { cloneDeep } from 'lodash';
import { LayerConfig, LayerSettings } from './types';

export const defaultOptions: LayerSettings = {
  left: 100,
  top: 50,
  translateX: 0,
  translateY: -50,
  translateZ: 0,
  rotateX: 0,
  rotateY: -50,
  rotateZ: -41,
  transformOriginX: -100,
  transformOriginY: 0,
  transformOriginZ: 0,
};

export const defaultPerspective = 300;

export const defaultGlobalSettings1: LayerConfig[] = [
  {
    label: 'Characters',
    color: 'black',
    bg: 'lightblue',
    visible: true,
    selected: true,
    isTextFlipped: false,
    layerSettings: { ...cloneDeep(defaultOptions), rotateZ: -36 },
  },
  {
    label: 'Shows',
    color: 'black',
    bg: 'orange',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: { ...cloneDeep(defaultOptions), rotateZ: -62 },
  },
  {
    label: 'Movies',
    color: 'black',
    bg: 'pink',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: { ...cloneDeep(defaultOptions), rotateZ: -18 },
  },
  {
    label: 'Video Games',
    color: 'black',
    bg: 'yellow',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: { ...cloneDeep(defaultOptions), rotateZ: 5 },
  },
  {
    label: 'Cards',
    color: 'black',
    bg: 'white',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: { ...cloneDeep(defaultOptions), rotateZ: 26 },
  },
];

export const defaultGlobalSettings2: LayerConfig[] = [
  {
    label: 'Characters',
    color: '#000000',
    bg: 'lightblue',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 16,
      translateY: -52,
      translateZ: 11,
      rotateX: 0,
      rotateY: -67,
      rotateZ: -16,
      transformOriginX: -100,
      transformOriginY: -39,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Shows',
    color: 'black',
    bg: 'orange',
    visible: true,
    selected: true,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 37,
      translateY: -64,
      translateZ: 30,
      rotateX: -7,
      rotateY: -52,
      rotateZ: -43,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Movies',
    color: 'black',
    bg: 'pink',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 1,
      translateY: -49,
      translateZ: 8,
      rotateX: 2,
      rotateY: -52,
      rotateZ: 11,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Video Games',
    color: 'black',
    bg: 'yellow',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -57,
      rotateZ: 29,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Cards',
    color: '#FFFFFF',
    bg: '#9514B3',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: -6,
      rotateX: 9,
      rotateY: -55,
      rotateZ: 60,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
];

export const defaultGlobalSettings3: LayerConfig[] = [
  {
    label: 'Characters',
    color: '#000000',
    bg: 'rgba(0, 192, 255, 0)',
    visible: true,
    selected: true,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 16,
      translateY: -52,
      translateZ: 44,
      rotateX: 0,
      rotateY: -59,
      rotateZ: -15,
      transformOriginX: -100,
      transformOriginY: -39,
      transformOriginZ: 8,
    },
  },
  {
    label: 'Shows',
    color: 'black',
    bg: 'rgba(255, 165, 0, 0)',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 37,
      translateY: -64,
      translateZ: 30,
      rotateX: -7,
      rotateY: -52,
      rotateZ: -36,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Movies',
    color: 'black',
    bg: 'rgba(255, 192, 203, 0)',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: -1,
      translateY: -50,
      translateZ: -4,
      rotateX: 2,
      rotateY: -56,
      rotateZ: 1,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Video Games',
    color: 'black',
    bg: 'rgba(255, 255, 0, 0)',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -57,
      rotateZ: 10,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Cards',
    color: 'rgba(0, 0, 0, 1)',
    bg: 'rgba(149, 20, 179, 0)',
    visible: true,
    selected: false,
    isTextFlipped: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: -6,
      rotateX: 9,
      rotateY: -55,
      rotateZ: 33,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
];

const defaultGlobalSettings4: LayerConfig[] = [
  {
    label: 'Skill',
    color: 'rgba(175, 45, 186, 1)',
    bg: 'rgba(173, 46, 184, 0)',
    visible: true,
    selected: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -50,
      rotateZ: -160,
      transformOriginX: -100,
      transformOriginY: -2,
      transformOriginZ: 0,
    },
    isTextFlipped: true,
  },
  {
    label: 'Item',
    color: 'rgba(24, 82, 184, 1)',
    bg: 'rgba(255, 165, 0, 0)',
    visible: true,
    selected: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -50,
      rotateZ: -169,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
    isTextFlipped: true,
  },
  {
    label: 'Equipment',
    color: 'rgba(242, 36, 77, 1)',
    bg: 'rgba(255, 192, 203, 0)',
    visible: true,
    selected: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -50,
      rotateZ: -182,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
    isTextFlipped: true,
  },
  {
    label: 'Party',
    color: 'rgba(44, 184, 163, 1)',
    bg: 'rgba(255, 255, 0, 0)',
    visible: true,
    selected: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -50,
      rotateZ: -192,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
    isTextFlipped: true,
  },
  {
    label: 'Follower',
    color: 'rgba(220, 227, 20, 1)',
    bg: 'rgba(255, 255, 255, 0)',
    visible: true,
    selected: false,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -50,
      rotateZ: -202,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
    isTextFlipped: true,
  },
  {
    label: 'Quest',
    color: 'rgba(245, 128, 2, 1)',
    bg: 'rgba(255, 255, 255, 0)',
    visible: true,
    selected: true,
    isTextFlipped: true,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: 0,
      translateY: -50,
      translateZ: 0,
      rotateX: 0,
      rotateY: -50,
      rotateZ: -212,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Calendar',
    color: 'rgba(131, 18, 230, 1)',
    bg: 'rgba(255, 255, 255, 0)',
    visible: true,
    selected: false,
    isTextFlipped: true,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: -9,
      translateY: -41,
      translateZ: -15,
      rotateX: -1,
      rotateY: -56,
      rotateZ: -223,
      transformOriginX: -100,
      transformOriginY: 0,
      transformOriginZ: 0,
    },
  },
  {
    label: 'Journal',
    color: 'rgba(5, 185, 235, 1)',
    bg: 'rgba(255, 255, 255, 0)',
    visible: true,
    selected: false,
    isTextFlipped: true,
    layerSettings: {
      left: 100,
      top: 46,
      translateX: -31,
      translateY: -39,
      translateZ: -56,
      rotateX: 4,
      rotateY: -66,
      rotateZ: -232,
      transformOriginX: -100,
      transformOriginY: -2,
      transformOriginZ: -10,
    },
  },
  {
    label: 'System',
    color: 'rgba(33, 224, 11, 1)',
    bg: 'rgba(255, 255, 255, 0)',
    visible: true,
    selected: false,
    isTextFlipped: true,
    layerSettings: {
      left: 100,
      top: 50,
      translateX: -46,
      translateY: -45,
      translateZ: -67,
      rotateX: 6,
      rotateY: -79,
      rotateZ: -226,
      transformOriginX: -100,
      transformOriginY: 1,
      transformOriginZ: -15,
    },
  },
];

export const globalSettingsList = [
  defaultGlobalSettings1,
  defaultGlobalSettings2,
  defaultGlobalSettings3,
  defaultGlobalSettings4,
];

export const defaultGlobalSettings = defaultGlobalSettings1;
